/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.proxy.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param recipientKey Random key of the end recipient of the proxied message.
 * @param sender 
 * @param message 
 * @param receivedAt 
 */


data class MessageProxyRequest (

    /* Random key of the end recipient of the proxied message. */
    @Json(name = "recipientKey")
    val recipientKey: kotlin.String,

    @Json(name = "sender")
    val sender: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "receivedAt")
    val receivedAt: kotlinx.datetime.Instant

) {


}

