/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.proxy.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `field` 
 * @param message 
 */


data class MessagesProxy422ResponseInvalidFieldsInner (

    @Json(name = "field")
    val `field`: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String

) {


}

