/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.proxy.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Unexpected internal server error occurred.
 *
 * @param code Machine-readable error code.
 * @param message Human-readable explanation of the error.
 */


data class MessagesProxy400Response (

    /* Machine-readable error code. */
    @Json(name = "code")
    val code: kotlin.Int,

    /* Human-readable explanation of the error. */
    @Json(name = "message")
    val message: kotlin.String

) {


}

