/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.proxy.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Parameters of a message recipient that can change over time.
 *
 * @param notificationsId Opaque identifier of the recipient in the notification system. For example, device token in Firebase Cloud Messaging.
 */


data class RecipientTransientParamsUpdate (

    /* Opaque identifier of the recipient in the notification system. For example, device token in Firebase Cloud Messaging. */
    @Json(name = "notificationsId")
    val notificationsId: kotlin.String? = null

) {


}

