/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.proxy.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param notificationsId Opaque identifier of the recipient in the notification system. For example, device token in Firebase Cloud Messaging.
 * @param recipientKey Random key of the recipient.
 * @param publicKey Public key of the recipient for encrypting sent out messages.
 */


data class RegisterRecipientRequest (

    /* Opaque identifier of the recipient in the notification system. For example, device token in Firebase Cloud Messaging. */
    @Json(name = "notificationsId")
    val notificationsId: kotlin.String,

    /* Random key of the recipient. */
    @Json(name = "recipientKey")
    val recipientKey: kotlin.String,

    /* Public key of the recipient for encrypting sent out messages. */
    @Json(name = "publicKey")
    val publicKey: kotlin.ByteArray

) {


}

