/**
 * Service for proxying messages
 * Service for proxying messages. Uses random API keys for authentication, which are passed as HTTP Bearer tokens.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package io.mrnateriver.smsproxy.models

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param receiverKey Random key of the end receiver of the proxied message.
 * @param sender 
 * @param message 
 * @param receivedAt 
 */


data class MessageProxyRequest (

    /* Random key of the end receiver of the proxied message. */

    @JsonProperty("receiverKey")
    val receiverKey: kotlin.String,


    @JsonProperty("sender")
    val sender: kotlin.String,


    @JsonProperty("message")
    val message: kotlin.String,


    @JsonProperty("receivedAt")
    val receivedAt: java.time.OffsetDateTime

)

