/**
 * Service for proxying messages
 * Service for proxying messages. Uses random API keys for authentication, which are passed as HTTP Bearer tokens.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package io.mrnateriver.smsproxy.models

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * Unexpected internal server error occurred.
 *
 * @param code Machine-readable error code.
 * @param message Human-readable explanation of the error.
 */


data class MessagesProxy400Response (

    /* Machine-readable error code. */

    @JsonProperty("code")
    val code: kotlin.Int,

    /* Human-readable explanation of the error. */

    @JsonProperty("message")
    val message: kotlin.String

)

