/**
 * Service for proxying messages
 * Service for proxying messages. Uses random API keys for authentication, which are passed as HTTP Bearer tokens.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package io.mrnateriver.smsproxy.models

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * Parameters of a message receiver that can change over time.
 *
 * @param notificationsId Opaque identifier of the receiver in the notification system. For example, device token in Firebase Cloud Messaging.
 */


data class ReceiverTransientParams (

    /* Opaque identifier of the receiver in the notification system. For example, device token in Firebase Cloud Messaging. */

    @JsonProperty("notificationsId")
    val notificationsId: kotlin.String? = null

)

