/**
 * Service for proxying messages
 * Service for proxying messages. Uses random API keys for authentication, which are passed as HTTP Bearer tokens.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package io.mrnateriver.smsproxy.models

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param notificationsId Opaque identifier of the receiver in the notification system. For example, device token in Firebase Cloud Messaging.
 * @param receiverKey Random key of the receiver.
 * @param publicKey Public key of the receiver for encrypting sent out messages.
 */


data class RegisterReceiverRequest (

    /* Opaque identifier of the receiver in the notification system. For example, device token in Firebase Cloud Messaging. */

    @JsonProperty("notificationsId")
    val notificationsId: kotlin.String,

    /* Random key of the receiver. */

    @JsonProperty("receiverKey")
    val receiverKey: kotlin.String,

    /* Public key of the receiver for encrypting sent out messages. */

    @JsonProperty("publicKey")
    val publicKey: kotlin.ByteArray

)

