{
 "title": "System Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Relayed Messages",
   "type": "stat",
   "description": "How many messages have been successfully relayed by the server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sms_proxy_processing_successes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relaying Errors",
   "type": "stat",
   "description": "Number of failed attempts to relay messages by server.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sms_proxy_processing_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Errors: Client",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sms_proxy_api_client_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Errors: Server",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sms_proxy_api_server_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Times",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Server Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{service_name=\"server-sms-proxy-1\"} | json | line_format `{{.formattedMessage}}`"
    }
   ]
  },
  {
   "title": "P95 Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, http_server_request_duration_seconds_bucket{http_response_status_code=~\"201|200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, http_server_request_duration_seconds_bucket{http_response_status_code=~\"201|200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=\"server-sms-proxy-1\",image!=\"\",container_label_io_mrnateriver_group=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Server RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{name=\"server-sms-proxy-1\",image!=\"\",container_label_io_mrnateriver_group=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}