---
apiVersion: v1
kind: Namespace
metadata:
  name: sms-proxy-flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github-mrnateriver
  namespace: sms-proxy-flux-system
spec:
  interval: 5m0s
  url: https://github.com/mrnateriver/sms-proxy
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: sms-proxy-flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/cert-manager
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: sms-proxy-flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/cert-manager-issuer
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-tls
  namespace: sms-proxy-flux-system
spec:
  dependsOn:
    - name: cert-manager-issuer
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/vault-tls
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: sms-proxy-flux-system
spec:
  dependsOn:
    - name: vault-tls
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/vault
  prune: true

# TODO: observability
# TODO: infrastructure
# TODO: app
