apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: sms-proxy
spec:
  interval: 60m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.4.8
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  values:
    syncSecret:
      enabled: true
