apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: sms-proxy-cert-manager
spec:
  interval: 60m
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  targetNamespace: sms-proxy-cert-manager
  values:
    installCRDs: true
