/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.models

import io.mrnateriver.smsproxy.models.MessagesProxy422ResponseInvalidFieldsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Value was formatted properly but contained invalid data.
 *
 * @param code Machine-readable error code.
 * @param message Human-readable explanation of the error.
 * @param invalidFields 
 */


data class MessagesProxy422Response (

    /* Machine-readable error code. */
    @Json(name = "code")
    val code: kotlin.Int,

    /* Human-readable explanation of the error. */
    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "invalidFields")
    val invalidFields: kotlin.collections.List<MessagesProxy422ResponseInvalidFieldsInner>

) {


}

