apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - issuer-root.yml
  - ca-root.yml
  - issuer-intermediate.yml
  - ca-intermediate.yml
  - issuer-leaf.yml

# The intention here was to fix any inadvertent typos or invalid values in namespaces, but it was considered just too repetitive for every namespace
# TODO: if there'd be a way to reference patches like functions with args, then perhaps this could be used
#patches:
#  - target:
#      kind: (.*)
#    patch: |
#      - op: replace
#        path: /metadata/namespace
#        value: sms-proxy-cert-manager
#  - target:
#      kind: HelmRelease
#    patch: |
#      - op: replace
#        path: /spec/targetNamespace
#        value: sms-proxy-cert-manager
#  - target:
#      kind: Namespace
#    patch: |
#      - op: replace
#        path: /metadata/name
#        value: sms-proxy-cert-manager
#      - op: remove
#        path: /metadata/namespace
