/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.mrnateriver.smsproxy.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param notificationsId Opaque identifier of the receiver in the notification system. For example, device token in Firebase Cloud Messaging.
 * @param receiverKey Random key of the receiver.
 * @param publicKey Base64-encoded public key of the receiver for encrypting sent out messages.
 */


data class RegisterReceiverRequest (

    /* Opaque identifier of the receiver in the notification system. For example, device token in Firebase Cloud Messaging. */
    @Json(name = "notificationsId")
    val notificationsId: kotlin.String,

    /* Random key of the receiver. */
    @Json(name = "receiverKey")
    val receiverKey: kotlin.String,

    /* Base64-encoded public key of the receiver for encrypting sent out messages. */
    @Json(name = "publicKey")
    val publicKey: kotlin.String

) {


}

