apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - name: Trace
          urlDisplayLabel: Trace
          datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
        spanEndTimeShift: "10m"
        spanStartTimeShift: "-10m"
        customQuery: true
        query: "{trace_id=\"$${__trace.traceId}\"}"
      tracesToMetrics:
        datasourceUid: prometheus
      spanBar:
        type: 'Tag'
        tag: 'http.path'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      streamingEnabled:
        search: true
