apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: sms-proxy-vault
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts

