kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: sms-proxy-vault
  name: vault-service-account-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "update", "patch" ]
