global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'traefik:9100' ]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'tempo'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'sms-proxy'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'sms-proxy:3000' ]

# Used for short-running jobs
#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']
