log:
  level: DEBUG
  format: common

api:
  insecure: true

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: false
  docker:
    exposedByDefault: false

entryPoints:
  server:
    address: ":3000"
    asDefault: true
  prometheus:
    address: ":9100"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/server.pem
        keyFile: /etc/traefik/certs/server-private-key.pem
  options:
    default:
      minVersion: VersionTLS12
      clientAuth:
        caFiles:
          - /etc/traefik/certs/clients/proxy-api-relay-app.pem
          - /etc/traefik/certs/clients/proxy-api-receiver-app.pem
        clientAuthType: RequireAndVerifyClientCert

metrics:
  addInternals: false
  prometheus:
    entryPoint: prometheus

tracing:
  addInternals: false
  capturedResponseHeaders:
    - X-Request-ID
  otlp:
    grpc:
      insecure: true
      endpoint: alloy:4317
