log:
  level: DEBUG
  format: json

api:
  insecure: true

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: false
  docker:
    exposedByDefault: false

entryPoints:
  server:
    address: ":3000"
    asDefault: true
  prometheus:
    address: ":9100"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/server.pem
        keyFile: /etc/traefik/certs/server-private-key.pem
  options:
    default:
      minVersion: VersionTLS12
      clientAuth:
        caFiles:
          - /etc/traefik/certs/clients/proxy-api-relay-app.pem
          - /etc/traefik/certs/clients/proxy-api-receiver-app.pem
        clientAuthType: RequireAndVerifyClientCert

metrics:
  addInternals: true
  prometheus:
    entryPoint: prometheus

#tracing: true
