apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github-mrnateriver
  namespace: sms-proxy
spec:
  interval: 5m0s
  url: https://github.com/mrnateriver/sms-proxy
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-init
  namespace: sms-proxy
spec:
  interval: 60m0s
  retryInterval: 1m
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/k8s/03-vault-init.yml
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: sms-proxy
spec:
  dependsOn:
    - name: vault-init
  interval: 60m0s
  retryInterval: 1m
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/k8s/04-postgresql.yml
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: sms-proxy
spec:
  dependsOn:
    - name: postgresql
  interval: 60m0s
  retryInterval: 1m
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/k8s/05-app.yml
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-migrations
  namespace: sms-proxy
spec:
  dependsOn:
    - name: app
  interval: 60m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: github-mrnateriver
  path: ./server/infra/prod/k8s/06-app-migrations.yml
  prune: true
  wait: true
  force: true

# TODO: observability
