apiVersion: v1
kind: Pod
metadata:
  name: jump-host
  namespace: sms-proxy
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"
