apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-root
  namespace: sms-proxy
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-intermediate
  namespace: sms-proxy
spec:
  ca:
    secretName: ca-key-pair-root
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-leaf
  namespace: sms-proxy
spec:
  ca:
    secretName: ca-key-pair-intermediate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
  namespace: sms-proxy
spec:
  isCA: true
  secretName: ca-key-pair-root
  subject:
    countries:
      - "NO"
    organizations:
      - "mrnateriver.io"
  commonName: "mrnateriver.io: Root CA"
  duration: 43800h
  renewBefore: 240h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: issuer-root
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-intermediate
  namespace: sms-proxy
spec:
  isCA: true
  secretName: ca-key-pair-intermediate
  subject:
    countries:
      - "NO"
    organizations:
      - "mrnateriver.io"
  commonName: "mrnateriver.io: Intermediate CA"
  duration: 8760h
  renewBefore: 240h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: issuer-intermediate
    kind: Issuer
