apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
  namespace: sms-proxy
spec:
  secretName: vault-tls-secret
  issuerRef:
    name: issuer-leaf
    kind: Issuer
  dnsNames:
    - "*.sms-proxy-vault-internal"
  ipAddresses:
    - 127.0.0.1
  duration: 2160h
  renewBefore: 360h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: sms-proxy
spec:
  interval: 1m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: sms-proxy
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: sms-proxy
spec:
  interval: 60m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.4.8
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  values:
    syncSecret:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: sms-proxy
spec:
  interval: 60m
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  releaseName: sms-proxy-vault
  values:
    global:
      enabled: true
      tlsDisable: false
    csi:
      enabled: true
    injector:
      enabled: false
    ui:
      enabled: true
      servicePort: 8200
      serviceType: ClusterIP
    server:
      affinity: "" # In HA mode pods have anti-affinity for each other; remove for the sake of experimentation in this project
      image:
        repository: hashicorp/vault
        tag: "1.18.1"
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      livenessProbe:
        enabled: true
        initialDelaySeconds: 60
        path: /v1/sys/health?standbyok=true
      readinessProbe:
        enabled: true
        path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
      standalone:
        enabled: false
      # TODO: network security policy
      #      networkPolicy:
      #        enabled: false
      auditStorage:
        enabled: true
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/vault-tls-secret/ca.crt
      extraVolumes:
        - name: vault-tls-secret
          type: secret
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            cluster_name = "sms-proxy-vault-cluster"
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
              tls_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
            }
            
            service_registration "kubernetes" {
              namespace = "sms-proxy"
            }

            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "https://sms-proxy-vault-0.sms-proxy-vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/vault-tls-secret/ca.crt"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
              retry_join {
                leader_api_addr = "https://sms-proxy-vault-1.sms-proxy-vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/vault-tls-secret/ca.crt"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
              retry_join {
                leader_api_addr = "https://sms-proxy-vault-2.sms-proxy-vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/vault-tls-secret/ca.crt"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
            }
