apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-tls-certificate
  namespace: sms-proxy
spec:
  secretName: postgresql-tls-secret
  issuerRef:
    name: issuer-leaf
    kind: Issuer
  dnsNames:
    - "*.sms-proxy-postgresql"
  ipAddresses:
    - 127.0.0.1
  duration: 2160h
  renewBefore: 360h
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-postgresql
  namespace: sms-proxy
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "16.4.7"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: sms-proxy
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
    namespace: sms-proxy
  interval: 1h
  values:
    volumePermissions:
      enabled: true
    tls:
      enabled: true
      preferServerCiphers: true
      certificatesSecret: postgresql-tls-secret
      certFilename: "tls.crt"
      certKeyFilename: "tls.key"
    auth:
      database: sms_proxy
      existingSecret: postgresql-admin-password
      secretKeys:
        adminPasswordKey: password
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: postgresql-admin-password
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  isKVSecretsEngineV2: false # It's a one-time password anyway, so we don't need KV v2; the root DB password will be rotated by Vault later
  path: kv/sms-proxy
  secretKey: password
  secretFormat:
    passwordPolicyName: default-password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: postgresql-admin-password
  namespace: sms-proxy
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: vault-operator
        serviceAccount:
          name: vault-operator-sa
      name: postgresql
      path: kv/sms-proxy/postgresql-admin-password
  output:
    name: postgresql-admin-password
    stringData:
      password: "{{ .postgresql.password }}"
    type: Opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: postgresql-secret-engine
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  type: database
  path: postgresql
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: postgresql-secret-engine
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  pluginName: postgresql-database-plugin
  allowedRoles:
    - postgresql-role-sms-proxy-app
  connectionURL: postgresql://{{username}}:{{password}}@postgresql.sms-proxy.svc.cluster.local:5432
  passwordPolicy: default-password-policy
  rootCredentials:
    secret:
      name: postgresql-admin-password
    passwordKey: password
  username: postgres
  path: postgresql/postgresql-secret-engine
  rootPasswordRotation:
    enable: true
    rotationPeriod: 24h0m0s
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: postgresql-role-sms-proxy-app
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  path: postgresql/postgresql-secret-engine
  # The full format is needed because otherwise Terraform fails due to inconsistent output
  # The short TTL should be plenty because we only need to establish a connection and then we don't care about the credentials' validity
  defaultTTL: 5m0s
  maxTTL: 10m0s
  dBName: postgresql-secret-engine
  creationStatements:
    - CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
    - GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA "public" TO "{{name}}";
  revocationStatements:
    - REVOKE ALL ON SCHEMA "public" FROM "{{name}}";
