apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-tls-certificate
  namespace: sms-proxy
spec:
  secretName: postgresql-tls-secret
  issuerRef:
    name: issuer-leaf
    kind: Issuer
  commonName: "postgresql-server"
  dnsNames:
    - "postgresql.sms-proxy.svc.cluster.local"
  duration: 2160h
  renewBefore: 360h
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: postgresql-admin-password
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  isKVSecretsEngineV2: false # It's a one-time password anyway, so we don't need KV v2; the root DB password will be rotated by Vault later
  path: kv/sms-proxy
  secretKey: password
  secretFormat:
    passwordPolicyName: default-password-policy
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgresql-admin-password
  namespace: sms-proxy
spec:
  type: kv-v1
  mount: kv
  path: sms-proxy/postgresql-admin-password
  destination:
    name: postgresql-admin-password
    create: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-postgresql
  namespace: sms-proxy
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "16.4.7"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: sms-proxy
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
    namespace: sms-proxy
  interval: 1h
  values:
    metrics:
      enabled: true
    volumePermissions:
      enabled: true
    tls:
      enabled: true
      preferServerCiphers: true
      certificatesSecret: postgresql-tls-secret
      certFilename: "tls.crt"
      certKeyFilename: "tls.key"
      certCAFilename: "ca.crt"
    auth:
      database: sms_proxy
      existingSecret: postgresql-admin-password
      secretKeys:
        adminPasswordKey: password
    primary:
      # This configuration effectively enables mTLS
      pgHbaConfiguration: |
        hostssl all all 0.0.0.0/0 scram-sha-256 clientcert=verify-ca
        hostssl all all ::/0 scram-sha-256 clientcert=verify-ca
        hostssl all all 127.0.0.1/32 scram-sha-256 clientcert=verify-ca
        hostssl all all ::1/128 scram-sha-256 clientcert=verify-ca
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: postgresql-secret-engine
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  type: database
  path: postgresql
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: postgresql-secret-engine
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  pluginName: postgresql-database-plugin
  allowedRoles:
    - postgresql-role-sms-proxy-app
    - postgresql-role-sms-proxy-migrations-job
  connectionURL: postgresql://{{username}}:{{password}}@postgresql.sms-proxy.svc.cluster.local:5432/sms_proxy?sslmode=verify-full&sslrootcert=/vault/userconfig/vault-tls-secret-postgresql-client/ca.crt&sslcert=/vault/userconfig/vault-tls-secret-postgresql-client/tls.crt&sslkey=/vault/userconfig/vault-tls-secret-postgresql-client/tls.key
  passwordPolicy: default-password-policy
  rootCredentials:
    secret:
      name: postgresql-admin-password
    passwordKey: password
  username: postgres
  path: postgresql/postgresql-secret-engine
  rootPasswordRotation:
    enable: true
    rotationPeriod: 24h0m0s
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: postgresql-role-sms-proxy-app
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  path: postgresql/postgresql-secret-engine
  # The full format is needed because otherwise Terraform fails due to inconsistent output
  defaultTTL: 12h0m0s
  maxTTL: 12h0m0s
  dBName: postgresql-secret-engine
  creationStatements:
    - CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
    - GRANT USAGE ON SCHEMA "public" TO "{{name}}";
    - GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA "public" TO "{{name}}";
  revocationStatements:
    - REVOKE ALL ON ALL TABLES IN SCHEMA "public" FROM "{{name}}";
    - REVOKE ALL ON SCHEMA "public" FROM "{{name}}";
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: postgresql-role-sms-proxy-migrations-job
  namespace: sms-proxy
spec:
  authentication:
    path: kubernetes
    role: vault-operator
    serviceAccount:
      name: vault-operator-sa
  path: postgresql/postgresql-secret-engine
  # The full format is needed because otherwise Terraform fails due to inconsistent output
  defaultTTL: 5m0s
  maxTTL: 5m0s
  dBName: postgresql-secret-engine
  creationStatements:
    - CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
    - GRANT ALL PRIVILEGES ON SCHEMA "public" TO "{{name}}";
    - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "{{name}}";
  revocationStatements:
    - REVOKE ALL ON ALL TABLES IN SCHEMA "public" FROM "{{name}}";
    - REVOKE ALL ON SCHEMA "public" FROM "{{name}}";
