apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: db-sms-proxy-migrations
  namespace: sms-proxy
spec:
  mount: postgresql
  path: postgresql/creds/sms-proxy-migrations
  destination:
    name: credentials-db-sms-proxy-migrations
    create: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-client-sms-proxy-migrations
  namespace: sms-proxy
spec:
  secretName: tls-postgresql-client-sms-proxy-migrations
  issuerRef:
    name: issuer-leaf
    kind: Issuer
  commonName: "sms-proxy"
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
    rotationPolicy: Always
  additionalOutputFormats:
    - type: DER
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-proxy-migrations
  namespace: sms-proxy
data:
  url: jdbc:postgresql://postgresql:5432/sms_proxy?sslmode=verify-full&sslrootcert=/var/run/secrets/tls-postgresql-client-sms-proxy-migrations/ca.crt&sslcert=/var/run/secrets/tls-postgresql-client-sms-proxy-migrations/tls.crt&sslkey=/var/run/secrets/tls-postgresql-client-sms-proxy-migrations/key.der
  schema: public
  connectRetries: "5"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sms-proxy-migrations
  namespace: sms-proxy
  labels:
    app.kubernetes.io/name: sms-proxy-migrations
    app.kubernetes.io/instance: sms-proxy-migrations-job
    app.kubernetes.io/component: sms-proxy-migrations
    app.kubernetes.io/part-of: sms-proxy
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sms-proxy-migrations
        app.kubernetes.io/instance: sms-proxy-migrations
        app.kubernetes.io/component: sms-proxy-migrations
        app.kubernetes.io/part-of: sms-proxy
    spec:
      restartPolicy: Never
      volumes:
        - name: tls-postgresql-client-sms-proxy-migrations
          secret:
            secretName: tls-postgresql-client-sms-proxy-migrations
      imagePullSecrets:
        - name: credentials-docker-oci-registry
      containers:
        - name: flyway
          image: "oci-registry:5000/sms-proxy/sms-proxy-migrations:latest"
          volumeMounts:
            - name: tls-postgresql-client-sms-proxy-migrations
              readOnly: true
              mountPath: "/var/run/secrets/tls-postgresql-client-sms-proxy-migrations"
          env:
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: sms-proxy-migrations
                  key: url
            - name: FLYWAY_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: sms-proxy-migrations
                  key: schema
            - name: FLYWAY_CONNECT_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: sms-proxy-migrations
                  key: connectRetries
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials-db-sms-proxy-migrations
                  key: username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials-db-sms-proxy-migrations
                  key: password
