name: Shared Unit Tests - AVD
description: Clones the repo, sets up JDK, prepares AVD and then runs the shared unit tests on it.
inputs:
  project:
    description: Module name. Used to determine test output directory.
    required: true
  api-level:
    description: 'API level of the Android Virtual Device.'
    default: '26' # minSdk from libs.versions.toml
runs:
  using: composite
  steps:
    - name: Setup JDK & Gradle
      uses: ./.github/actions/prepare-gradle

    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        echo SENTRY_DSN=$SENTRY_DSN

    - name: AVD cache
      id: avd-cache
      uses: actions/cache@v4
      with:
        key: avd-${{ inputs.api-level }}
        path: |
          ~/.android/avd/*
          ~/.android/adb*

    - name: Run Android tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        ADB_INSTALL_TIMEOUT: 600 # 10 minutes (2 minutes by default)
      with:
        api-level: ${{ inputs.api-level }}
        arch: x86_64
        profile: Nexus 6
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: ./gradlew ${{ inputs.project }}:connectedDebugAndroidTest

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.project }}-avd-${{ inputs.api-level }}-test-report
        path: '${{ inputs.project }}/build/reports/androidTests/connected/debug'

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.project }}-avd-${{ inputs.api-level }}-test-results
        path: '${{ inputs.project }}/build/outputs/androidTest-results/connected/debug'
