name: Prepare Environment
description: Clones the repo, sets up JDK and prepares Gradle Wrapper for execution.
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: microsoft

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-overwrite-existing: true

    - name: Grant execute permission for ./gradlew
      run: chmod +x gradlew
      shell: sh
