apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
  namespace: sms-proxy-vault
spec:
  secretName: vault-tls-secret
  issuerRef:
    name: issuer-leaf
    kind: ClusterIssuer
  dnsNames:
    - "*.vault-test-internal" # FIXME: proper DNS
  ipAddresses:
    - 127.0.0.1
  duration: 2160h
  renewBefore: 360h
