name: Build
on:
  workflow_call:
    inputs:
      release:
        description: 'Whether to build a signed release APK, or merely perform a build without assembling an APK.'
        type: boolean
        default: false

jobs:
  build-relay:
    name: Relay Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      - name: Decode Keystore
        if: ${{ github.event.inputs.release }}
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_STORE_BASE64 }}
        run: |
          echo $ENCODED_STRING | base64 -di > release.keystore

      # TODO: export an artifact
      - name: Build signed release APK
        if: ${{ github.event.inputs.release }}
        env:
          RELEASE_STORE_PATH: release.keystore
          RELEASE_STORE_KEY_ALIAS: ${{ secrets.RELEASE_STORE_KEY_ALIAS }}
          RELEASE_STORE_KEY_PASSWORD: ${{ secrets.RELEASE_STORE_KEY_PASSWORD }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        run: ./gradlew relayApp:assembleRelease

      - name: Check build
        if: ${{ !github.event.inputs.release }}
        run: ./gradlew relayApp:build

  build-receiver:
    name: Receiver Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      - name: Decode Keystore
        if: ${{ github.event.inputs.release }}
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_STORE_BASE64 }}
        run: |
          echo $ENCODED_STRING | base64 -di > release.keystore

      # TODO: export an artifact
      - name: Build signed release APK
        if: ${{ github.event.inputs.release }}
        env:
          RELEASE_STORE_PATH: release.keystore
          RELEASE_STORE_KEY_ALIAS: ${{ secrets.RELEASE_STORE_KEY_ALIAS }}
          RELEASE_STORE_KEY_PASSWORD: ${{ secrets.RELEASE_STORE_KEY_PASSWORD }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        run: ./gradlew receiverApp:assembleRelease

      - name: Check build
        if: ${{ !github.event.inputs.release }}
        run: ./gradlew relayApp:build

  build-server:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      # TODO: build container image, yield image hash
      - name: Build release image
        if: ${{ github.event.inputs.release }}
        run: ./gradlew server:build # FIXME: proper Gradle task name

      - name: Check build
        if: ${{ github.event.inputs.release }}
        run: ./gradlew server:build
