name: Build - Relay App
on:
  workflow_call:
    inputs:
      release:
        description: 'Whether to build a signed release APK, or merely perform a build without assembling an APK.'
        type: boolean
        default: false
      project:
        description: 'Name of the Gradle project to build.'
        type: string
        required: true
      app-private-key:
        description: 'Private key of a TLS certificate that the app will use for mTLS with the server.'
        type: string
        required: true
      app-certificate:
        description: 'TLS certificate that the app will use for mTLS with the server.'
        type: string
        required: true
      sentry-dsn:
        description: 'Sentry DSN.'
        type: string
        required: false

jobs:
  build-app:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build the app
        uses: ./.github/actions/build-android
        with:
          project: ${{ inputs.project }}
          release: ${{ inputs.release }}
          release-keystore: ${{ secrets.RELEASE_STORE_BASE64 }}
          app-private-key: ${{ inputs.app-private-key }}
          app-certificate: ${{ inputs.app-certificate }}
          server-certificate: ${{ env.SERVER_CERTIFICATE_PEM }}
          release-store-key-alias: ${{ secrets.RELEASE_STORE_KEY_ALIAS }}
          release-store-key-password: ${{ secrets.RELEASE_STORE_KEY_PASSWORD }}
          release-store-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-dsn: ${{ inputs.sentry-dsn }}
          api-key: ${{ secrets.SERVER_API_KEY }}
