name: Build - Server
on:
  workflow_call:
    inputs:
      release:
        description: 'Whether the build is being performed to issue a release, rather than just a check.'
        type: boolean
        default: false

jobs:
  build-server:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      - name: Add TLS certificates and keys
        if: ${{ inputs.release }}
        env:
          SERVER_PRIVATE_KEY_JKS_BASE64: ${{ secrets.SERVER_PRIVATE_KEY_JKS_BASE64 }}
        run: |
          echo $RELAY_APP_CERTIFICATE_PEM > ./server/src/main/assets/clients/proxy-api-relay-app.pem
          echo $RECEIVER_APP_CERTIFICATE_PEM > ./server/src/main/assets/clients/proxy-api-receiver-app.pem
          echo $SERVER_PRIVATE_KEY_JKS_BASE64 | base64 -d > ./server/src/main/assets/server.jks

      # TODO: build container image, yield image hash
      - name: Build release image
        if: ${{ inputs.release }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN_SERVER }}
        run: ./gradlew server:assemble # FIXME: proper Gradle task name

      - name: Check build
        if: ${{ !inputs.release }}
        run: ./gradlew server:assemble
