name: Build - Relay App
on:
  workflow_call:
    inputs:
      release:
        description: 'Whether to build a signed release APK, or merely perform a build without assembling an APK.'
        type: boolean
        default: false
      project:
        description: 'Name of the Gradle project to build.'
        type: string
        required: true
      app-certificate:
        description: 'TLS certificate that the app will use for mTLS with the server.'
        type: string
        required: true
    secrets:
      app-private-key:
        description: 'Private key of a TLS certificate that the app will use for mTLS with the server.'
        required: true
      release-keystore:
        description: Base64-encoded keystore file.
        required: true
      release-store-key-alias:
        description: Alias of the key in the keystore.
        required: true
      release-store-key-password:
        description: Password of the key in the keystore.
        required: true
      release-store-password:
        description: Password of the keystore.
        required: true
      sentry-auth-token:
        description: Sentry authentication token.
        required: true
      api-key:
        description: API key that is used on the server.
        required: true
      sentry-dsn:
        description: 'Sentry DSN.'
        required: false

jobs:
  build-app:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build the app
        uses: ./.github/actions/build-android
        with:
          server-certificate: ${{ vars.SERVER_CERTIFICATE_PEM }}
          project: ${{ inputs.project }}
          release: ${{ inputs.release }}
          app-certificate: ${{ inputs.app-certificate }}
          app-private-key: ${{ secrets.app-private-key }}
          release-keystore: ${{ secrets.release-keystore }}
          release-store-key-alias: ${{ secrets.release-store-key-alias }}
          release-store-key-password: ${{ secrets.release-store-key-password }}
          release-store-password: ${{ secrets.release-store-password }}
          sentry-auth-token: ${{ secrets.sentry-auth-token }}
          sentry-dsn: ${{ secrets.sentry-dsn }}
          api-key: ${{ secrets.api-key }}
