name: Linting - Server
on:
  workflow_call:
    inputs:
      project:
        description: 'Name of the Gradle project to lint.'
        type: string
        required: true

# TODO: switch to type resolution mode when Detekt 2.0 is released and the issue with commonTest is fixed
#       https://github.com/detekt/detekt/issues/4036

jobs:
  lint-shared:
    name: Lint Shared
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      - name: Run Detekt
        run: ./gradlew shared:detekt

  lint-project:
    name: Lint ${{ inputs.project }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      - name: Run Detekt
        run: ./gradlew ${{ inputs.project }}:detekt
