name: Main - Server

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "proxyApiTypeSpec/**"
      - "proxyApiServer/**"
      - "server/**"
      - "shared/**"
      - "settings.gradle.kts"
      - "build.gradle.kts"

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests-server.yml
    needs: [ check-codegen ]

  build:
    name: Builds
    uses: ./.github/workflows/build-server.yml
    needs: [ tests ]
    secrets: inherit
    with:
      release: true

  publish:
    name: Release
    uses: ./.github/workflows/release-server.yml
    needs: [ build ]
    secrets: inherit
