name: Main

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    needs: [ check-codegen ]

  build:
    name: Builds
    uses: ./.github/workflows/build.yml
    needs: [ tests ]
    secrets: inherit
    with:
      release: true

  publish:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: [ build ]
    secrets: inherit
