name: Main - Relay App

on:
  push:
    branches: [ "main" ]
    paths:
      - "proxyApiTypeSpec/**"
      - "proxyApiClient/**"
      - "relayApp/**"
      - "shared/**"

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests-android.yml
    needs: [ check-codegen ]
    with:
      project: relayApp
      sentry-dsn: ${{ env.SENTRY_DSN_RELAY }}

  build:
    name: Builds
    uses: ./.github/workflows/build-android.yml
    needs: [ tests ]
    secrets: inherit
    with:
      release: false # TODO: temporarily disabled until a secure release channel is created
      project: relayApp
      sentry-dsn: ${{ env.SENTRY_DSN_RELAY }}
      app-private-key: ${{ secrets.RELAY_APP_PRIVATE_KEY_PEM }}
      app-certificate: ${{ env.RELAY_APP_CERTIFICATE_PEM }}

  publish:
    name: Release
    uses: ./.github/workflows/release-android.yml
    needs: [ build ]
    secrets: inherit
