name: Main - Relay App

on:
  push:
    branches: [ "main" ]
    paths:
      - "proxyApiTypeSpec/**"
      - "proxyApiClient/**"
      - "relayApp/**"
      - "shared/**"

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests-android.yml
    needs: [ check-codegen ]
    with:
      project: relayApp

  build:
    name: Builds
    uses: ./.github/workflows/build-relayApp.yml
    needs: [ tests ]
    secrets: inherit
    with:
      release: false # TODO: temporarily disabled until a secure release channel is created

  publish:
    name: Release
    uses: ./.github/workflows/release-android.yml
    needs: [ build ]
    secrets: inherit
