name: Main - Receiver App

on:
  push:
    branches: [ "main" ]
    paths:
      - "proxyApiTypeSpec/**"
      - "proxyApiClient/**"
      - "receiverApp/**"
      - "shared/**"

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests-android.yml
    needs: [ check-codegen ]
    with:
      project: receiverApp
      sentry-dsn: ${{ vars.SENTRY_DSN_RECEIVER }}

  build:
    name: Builds
    uses: ./.github/workflows/build-android.yml
    needs: [ tests ]
    with:
      release: false # TODO: temporarily disabled until a secure release channel is created
      project: receiverApp
      sentry-dsn: ${{ vars.SENTRY_DSN_RECEIVER }}
      app-certificate: ${{ vars.RECEIVER_APP_CERTIFICATE_PEM }}
    secrets:
      release-keystore: ${{ secrets.RELEASE_STORE_BASE64 }}
      release-store-key-alias: ${{ secrets.RELEASE_STORE_KEY_ALIAS }}
      release-store-key-password: ${{ secrets.RELEASE_STORE_KEY_PASSWORD }}
      release-store-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
      sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
      api-key: ${{ secrets.SERVER_API_KEY }}
      app-private-key: ${{ secrets.RECEIVER_APP_PRIVATE_KEY_PEM }}

  publish:
    name: Release
    uses: ./.github/workflows/release-android.yml
    needs: [ build ]
    secrets: inherit
