name: Pull Request - Relay App

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "proxyApiTypeSpec/**"
      - "proxyApiClient/**"
      - "relayApp/**"
      - "shared/**"
      - "settings.gradle.kts"
      - "build.gradle.kts"

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    with:
      pr: true
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests-android.yml
    needs: [ check-codegen ]
    with:
      project: relayApp
    secrets:
      sentry-dsn: ${{ vars.SENTRY_DSN_RELAY }}

  linting:
    name: Linting
    uses: ./.github/workflows/linting.yml
    needs: [ check-codegen ]
    with:
      project: relayApp

  build:
    name: Build
    uses: ./.github/workflows/build-android.yml
    needs: [ check-codegen ]
    with:
      release: false
      project: relayApp
