name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    name: Security
    uses: ./.github/workflows/reusable/security.yml

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/reusable/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/reusable/tests.yml
    needs: [ check-codegen ]

  # TODO: linting!

  build:
    name: Builds
    uses: ./.github/workflows/reusable/build.yml
    needs: [ check-codegen ]
    with:
      release: false
