name: Pull Request - Server

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "proxyApiTypeSpec/**"
      - "proxyApiClient/**"
      - "server/**"
      - "shared/**"
      - "settings.gradle.kts"
      - "build.gradle.kts"

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml
    with:
      pr: true
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests-server.yml
    needs: [ check-codegen ]

  linting:
    name: Linting
    uses: ./.github/workflows/linting.yml
    needs: [ check-codegen ]
    with:
      project: server

  build:
    name: Builds
    uses: ./.github/workflows/build-server.yml
    needs: [ check-codegen ]
    with:
      release: false
