name: Create Release - Android
on:
  workflow_call:

jobs:
  release-android:
    name: Android Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Download Android builds
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: release-apk-*
          merge-multiple: true

      # TODO: set release version in env vars for later steps
      - name: Semantic Release
        run: npx -y semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
