name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yml

  check-codegen:
    name: Codegen
    uses: ./.github/workflows/check-codegen.yml
    needs: [ security ]

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    needs: [ check-codegen ]

  build:
    name: Builds
    uses: ./.github/workflows/build.yml
    needs: [ tests ]
    with:
      release: true

  publish:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      # TODO: deploy the server
      # TODO: tag the commit
      # TODO: create a GitHub release (+ semantic-release)
      - name: Publish release
        run: echo "TODO"
