name: Security Checks
on:
  workflow_call:
    secrets:
      snyk-token:
        description: 'Snyk API token for security scanning.'
        required: true
    inputs:
      pr:
        description: 'Whether the workflow is executed for a PR, as opposed to a protected branch.'
        type: boolean
        default: false

jobs:
  secrets:
    name: Secret Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.pr }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified

  sast:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Snyk
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          args: --severity-threshold=high --all-sub-projects
