name: Security Checks
on:
  workflow_call:
    inputs:
      pr:
        description: 'Whether the workflow is executed for a PR, as opposed to a protected branch.'
        type: boolean
        default: false

jobs:
  secrets:
    name: Secret Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.pr }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified --fail

  sast:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # TODO: SAST
      - name: Run SAST
        run: echo "TODO"

  dependencies:
    name: Dependencies Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # TODO: Dependabot maybe? Or Renovate? Either way, fail on critical CVEs
      - name: Check dependencies for CVEs
        run: echo "TODO"
