name: Security Checks
on:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # TODO: SAST
      - name: Run SAST
        run: echo "TODO"

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # TODO: Dependabot maybe? Or Renovate? Either way, fail on critical CVEs
      - name: Check dependencies for CVEs
        run: echo "TODO"
