name: Security Checks
on:
  workflow_call:
    secrets:
      snyk-token:
        description: 'Snyk API token for security scanning.'
        required: true
    inputs:
      pr:
        description: 'Whether the workflow is executed for a PR, as opposed to a protected branch.'
        type: boolean
        default: false

jobs:
  secrets:
    name: Secret Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.pr }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified

  snyk-test:
    name: Snyk - OSS & License Checks
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.snyk-token }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: OSS & License Checks
        uses: snyk/actions/gradle@master
        with:
          command: test
          args: --severity-threshold=high --all-sub-projects

      - name: Report findings
        uses: snyk/actions/gradle@master
        with:
          command: monitor
          args: --severity-threshold=high --all-sub-projects

  snyk-iac:
    name: Snyk - IAC
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.snyk-token }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: IAC
        uses: snyk/actions/gradle@master
        with:
          command: iac test
          args: --severity-threshold=high

  snyk-code:
    name: Snyk - Code
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.snyk-token }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Code
        uses: snyk/actions/gradle@master
        with:
          command: code test
          args: --severity-threshold=high --all-sub-projects
