name: Unit Tests - Server
on:
  workflow_call:

jobs:
  tests-shared-jvm:
    name: Shared Unit Tests - JVM
    runs-on: ubuntu-latest
    steps:
      - name: Shared Unit Tests - JVM
        uses: ./.github/actions/tests-shared-jvm

  tests-server:
    name: Server Unit Tests - JVM
    runs-on: ubuntu-latest
    needs: [ tests-shared-jvm ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle
        uses: ./.github/actions/prepare-gradle

      - name: Run JVM tests
        run: ./gradlew server:test

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-test-report
          path: 'server/build/reports/tests/test'

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-test-results
          path: 'server/build/test-results/test'
