name: Unit Tests - Android
on:
  workflow_call:
    inputs:
      project:
        description: 'Name of the Gradle project to lint.'
        type: string
        required: true

jobs:
  tests-shared-jvm:
    name: Shared Unit Tests - JVM
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Shared Unit Tests - JVM
        uses: ./.github/actions/tests-shared-jvm

  tests-shared-avd:
    name: Shared Unit Tests - AVD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1 # Looks like free tier of GH Actions cannot realistically run more than 1 AVD
      matrix:
        api-level: [ '26', '34' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Shared Unit Tests - AVD
        uses: ./.github/actions/tests-avd
        with:
          api-level: ${{ matrix.api-level }}
          project: shared

  tests-app:
    name: Unit Tests - AVD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1 # Looks like free tier of GH Actions cannot realistically run more than 1 AVD
      matrix:
        api-level: [ '26', '34' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run instrumented tests
        uses: ./.github/actions/tests-avd
        with:
          api-level: ${{ matrix.api-level }}
          project: ${{ inputs.project }}
